title: Adam Becker
description: "Code, bikes, soccer, Oakland. Currently building the <a href="http://www.dobt.co">Department of Better Technology</a>."
permalink: pretty
server: true
auto: true
pygments: true
